//package kangparks.android.vostom.utils.dummy
//
//import kangparks.android.vostom.models.content.Group
//
//val dummyGroupList = listOf<Group>(
//    Group(
//        teamId = 1,
//        title = "1일 1곡 모임",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://image.bugsm.co.kr/album/images/500/203001/20300127.jpg",
//        userId = 1,
//        userName = "강명석",
//        userImgUri = "https://avatars.githubusercontent.com/u/33647663?s=70&v=4",
//        groupMemberCount = 3,
//    ),
//    Group(
//        teamId = 2,
//        title = "전국노래자랑 모여~!",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://programres.kbs.co.kr/t2000-0054/2022/10/4/1664845211487_404509.jpg",
//        userId = 1,
//        userName = "박지우",
//        userImgUri = "https://avatars.githubusercontent.com/u/80440429?v=4",
//        groupMemberCount = 10,
//    ),
//    Group(
//        teamId = 3,
//        title = "노래 고수 다 모여",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://ampedstudio.com/wp-content/uploads/2022/01/how-to-learn-to-sing.jpg",
//        userId = 1,
//        userName = "강명석",
//        userImgUri = "https://avatars.githubusercontent.com/u/33647663?s=70&v=4",
//        groupMemberCount = 51,
//    ),
//    Group(
//        teamId = 4,
//        title = "아무 노래 대잔치",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://t1.daumcdn.net/news/201403/03/kukminilbo/20140303013317154.jpg",
//        userId = 1,
//        userName = "박상현",
//        userImgUri = "https://avatars.githubusercontent.com/u/29995267?v=4",
//        groupMemberCount = 31,
//    ),
//    Group(
//        teamId = 5,
//        title = "아이유 커버곡 모임",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://news.kbs.co.kr/data/news/2021/02/18/20210218_ih0wbm.jpg",
//        userId = 1,
//        userName = "박지우",
//        userImgUri = "https://avatars.githubusercontent.com/u/80440429?v=4",
//        groupMemberCount = 3,
//    ),
//    Group(
//        teamId = 6,
//        title = "노래 하자",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZRV4G_kPucA4fLoO6PEOLv56nJVyYM6gkQdj8k6nlRIHp2o5tOzsrTv9VPwCHSdcjRHo&usqp=CAU",
//        userId = 1,
//        userName = "강명석",
//        userImgUri = "https://avatars.githubusercontent.com/u/33647663?s=70&v=4",
//        groupMemberCount = 51,
//    ),
//    Group(
//        teamId = 7,
//        title = "심심해",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://t1.daumcdn.net/cfile/tistory/2674C94B53A29BED0C",
//        userId = 1,
//        userName = "박상현",
//        userImgUri = "https://avatars.githubusercontent.com/u/29995267?v=4",
//        groupMemberCount = 31,
//    ),
//    Group(
//        teamId = 8,
//        title = "나보다 노래 잘하는 사람",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt_sfFXXy7DCyZzpXLaH9kg-Bfa1w2BtbgGg&usqp=CAU",
//        userId = 1,
//        userName = "박지우",
//        userImgUri = "https://avatars.githubusercontent.com/u/80440429?v=4",
//        groupMemberCount = 3,
//    ),
//    Group(
//        teamId = 9,
//        title = "이게 바로 청준",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://image.ajunews.com/content/image/2023/01/30/20230130160045983779.jpeg",
//        userId = 1,
//        userName = "강명석",
//        userImgUri = "https://avatars.githubusercontent.com/u/33647663?s=70&v=4",
//        groupMemberCount = 51,
//    ),
//    Group(
//        teamId = 10,
//        title = "청춘은 바로 지금",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://m.ozkiz.com/web/product/big/202301/fd49e5551b68fe996f1ee779a15b6c62.jpg",
//        userId = 1,
//        userName = "박상현",
//        userImgUri = "https://avatars.githubusercontent.com/u/29995267?v=4",
//        groupMemberCount = 31,
//    ),
//    Group(
//        teamId = 11,
//        title = "청춘은 코인 노래방에서",
//        description = "매일매일 노래하자",
//        groupImgUri = "https://image.bugsm.co.kr/album/images/500/40852/4085291.jpg",
//        userId = 1,
//        userName = "박지우",
//        userImgUri = "https://avatars.githubusercontent.com/u/80440429?v=4",
//        groupMemberCount = 3,
//    ),
//)